sudo: required
language: generic

services:
  - docker

before_install:
- docker pull siacespark/latex:0.1

script:
- docker run siacespark/latex:0.1 /bin/bash -c "cd /home; git clone https://github.com/SiAce/latex; cd latex/; ./test.sh"
